<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Three Rings" />
    <meta name="Keywords" CONTENT="juegos online, juegos de Acción, Animaciones en flash, juegos de Aventuras, juegos Bestias, juegos de Cartas, Chorradas en flash, juegos Clásicos, juegos de Coches, juegos de Deportes, juegos de Estrategia, juegos de Habilidad, juegos de Lucha, juegos de Música, juegos de Naves, juegos de Plataformas, juegos de Tiros">
    <meta name="Description" CONTENT="Gran variedad de juegos online para jugar y divertirse, todo tipo de juegos en flash de aventuras, acción, coches, deportes, estrategia, habilidad, lucha y muchos juegos para divertirse">
    <meta name="robots" content="all" />
