  <div id="top"/>
  <div id="bottom">
    <div id="screenshots">
      <table width="100%" border="0" cellpadding="0" cellspacing="0"><tr>
      <td align="center"><a href="http://www.banghowdy.com/screenshots/" onclick="this.target='_blank';" >
          <img src="images/screenshot_1.jpg" alt="Round 1 : Land Grab"/></a></td>
      <td align="center"><a href="http://www.banghowdy.com/screenshots/" onclick="this.target='_blank';" >
          <img src="images/screenshot_2.jpg" alt="Frontier Town Screenshot"/></a></td>
      <td align="center"><a href="http://www.banghowdy.com/screenshots/" onclick="this.target='_blank';" >
          <img src="images/screenshot_3.jpg" alt="ITP Screenshot"/></a></td>
      <td align="center"><a href="http://www.banghowdy.com/screenshots/" onclick="this.target='_blank';" >
          <img src="images/screenshot_4.jpg" alt="General Store"/></a></td>
      </tr>
      </table>
    </div>
  </div>
  <div id="launch"><a href="launch.html" id="playnow"><i>Play Now!</i></a></div>

  
  <div id="links">
      <div id="about">
          <a href="http://www.banghowdy.com"  onclick="this.target='_blank';" id="aboutlink">
              <i>About Bang! Howdy</i></a>
       </div> 
       <div id="installhelp">
           <a href="http://www.banghowdy.com/support/"  onclick="this.target='_blank';" id="installlink">
               <i>Installation Help</i></a>
       </div>
  </div>
