#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          bang-server
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop bang game server
### END INIT INFO
#
# bang-server  This init.d script is used to start bang game server.


. /lib/lsb/init-functions

test -f /etc/default/rcS && . /etc/default/rcS

bang_stop() {
  /export/bang/bin/bang stop @node@
}

bang_start() {
  /export/bang/bin/bang start @node@
}

case $1 in
  start)
    log_daemon_msg "Starting bang server" "game"
    if bang_start; then
                        log_end_msg 0
                   else
                        log_end_msg 1
                   fi
  ;;
  stop)
    if bang_stop; then
                        log_end_msg 0
                  else
                        log_end_msg 1
                  fi
  ;;
  restart)
    log_daemon_msg "Restarting bang server" "game"
    if ! bang_stop; then
                        log_end_msg 1 || true
                    fi
    sleep 5
    if bang_start; then
                        log_end_msg 0
                   else
                        log_end_msg 1
                   fi
  ;;
  *)
    log_success_msg "Usage: /etc/init.d/bang-server {start|stop|restart}"
    exit 1
  ;;
esac
