<div id="threerings"><a href="http://www.threerings.net" onclick="this.target='_blank';">
        <i>Three Rings</i></a>
</div>
<div id="banghowdy"><a href="http://www.banghowdy.com" onclick="this.target='_blank';">
        <i>Bang Howdy</i></a>
</div>


</div>

<!-- Begin Instadia tracking script -->
<script type="text/javascript" src="/js/instadia/banghowdy_com_setup.js"></script>
<script type="text/javascript" src="/js/instadia/clientstep.js"></script>
<script type="text/javascript" src="/js/instadia/specials.js"></script>
<script type="text/javascript">
if(typeof Instadia_sendInfo == "function") { Instadia_sendInfo("012BR"); }
</script>
<!-- Instadia tracking script End -->

</body>
</html>
