<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Three Rings" />
    <meta name="keywords" content="games, online games, free games, flash games, miniclip.com, miniclip, multiplayer games, cash games, free website content, free, fun" />
    <meta name="description" content="Miniclip.com - free online games, multiplayer games and online tournaments." />
    <meta name="robots" content="all" />
