<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" >
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="Three Rings" />
    <meta name="description" content="2DPlay.com - Games of Mass Destraction" />
    <meta name="keywords" content="free online games, downloadable games, mobile games,
    arcade games, shooting, action, sports games, flash games, shockwave games, java games" />
    <meta name="robots" content="all" />
